### ISSUE TITLE
style.css is missing in deb package

### ISSUE THREAD

**Issue by ghost** [kuthulux/gnome-connection-manager#71]
Hello,
the "style.css" is missing in deb package.
Please fix it.

Best Regards

**Comment by jimklimov** [comment]
Addressed by PR#70 collaterally

**Comment by Knutowskie** [comment]
Still missing. Downloaded latest version, installed on Debian 11. After installing the depencies manually (dpkg --install didn't want to install at all) i finally got it to install the deb package. After starting nothing happened.

I checked syslogs and the style.css was missing. i created one manually and now it works.

**Comment by yma-het** [comment]
Fixed here:
https://github.com/kuthulux/gnome-connection-manager/commit/9886cc2f8cae36ba176885db26ffe555ae27b306

**Comment by jimklimov** [comment]
I think it was premature to close this issue: the fix is not in a tagged/released version yet, so not delivered by vanilla packages. And this ticket was about DEBs...

**Comment by yma-het** [comment]
Yeah, you are right. I'll reopen and edit issue name.
What about packaging:
https://github.com/kuthulux/gnome-connection-manager/commit/9886cc2f8cae36ba176885db26ffe555ae27b306#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R45
debianization uses "install" makefile target and fpm, so in theory there is no specific actions needed to  include this file into the package.
